import type { Match } from "./types";

export const MATCHES: Match[] = [
  {
    id: "m-001",
    homeTeam: "Northside FC",
    awayTeam: "Royal Athletic",
    homeBadge: "🦁",
    awayBadge: "👑",
    competition: "Premier League — Matchday 24",
    date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 3).toISOString(),
    stadium: "Ironforge Arena",
    city: "Manchester",
    price: 65,
    totalSeats: 42000,
    soldSeats: 31200,
    heroColor: "from-emerald-500/30 to-cyan-500/20",
  },
  {
    id: "m-002",
    homeTeam: "Coastal United",
    awayTeam: "Highland Rangers",
    homeBadge: "⚓",
    awayBadge: "🏔️",
    competition: "Champions Cup — Quarter Final",
    date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 7).toISOString(),
    stadium: "Seabreeze Stadium",
    city: "Brighton",
    price: 120,
    totalSeats: 35000,
    soldSeats: 28900,
    heroColor: "from-blue-500/30 to-violet-500/20",
  },
  {
    id: "m-003",
    homeTeam: "Capital Wolves",
    awayTeam: "Old Town SC",
    homeBadge: "🐺",
    awayBadge: "🏰",
    competition: "Domestic Cup — Round of 16",
    date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 12).toISOString(),
    stadium: "Capital Dome",
    city: "London",
    price: 45,
    totalSeats: 60000,
    soldSeats: 18400,
    heroColor: "from-amber-500/30 to-rose-500/20",
  },
  {
    id: "m-004",
    homeTeam: "Sunset Galaxy",
    awayTeam: "Riverside FC",
    homeBadge: "🌅",
    awayBadge: "🌊",
    competition: "Premier League — Matchday 25",
    date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 18).toISOString(),
    stadium: "Galaxy Park",
    city: "Los Angeles",
    price: 80,
    totalSeats: 28000,
    soldSeats: 9100,
    heroColor: "from-fuchsia-500/30 to-orange-500/20",
  },
  {
    id: "m-005",
    homeTeam: "Iron Eagles",
    awayTeam: "Black Forest FC",
    homeBadge: "🦅",
    awayBadge: "🌲",
    competition: "Friendly International",
    date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 22).toISOString(),
    stadium: "Eagle Nest",
    city: "Berlin",
    price: 35,
    totalSeats: 50000,
    soldSeats: 12000,
    heroColor: "from-slate-500/30 to-emerald-500/20",
  },
];

export function getMatch(id: string) {
  return MATCHES.find((m) => m.id === id);
}